# 워크플로우의 이름
name: Deploy React App to S3

# 워크플로우가 언제 실행될지 정의하는 부분
on:
    push:
        branches:
            - main # ✅ main 브랜치에 push 될 때만 실행됩니다. (master 브랜치면 master로 변경)

# 실제 수행할 작업(Job)들
jobs:
    build-and-deploy:
        # 작업이 실행될 환경 (최신 우분투)
        runs-on: ubuntu-latest

        # 작업의 단계(Step)들
        steps:
            # 1. 레포지토리 코드 체크아웃
            - name: Checkout
              uses: actions/checkout@v3

            # 2. Node.js 환경 설정
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18" # ✅ 본인 프로젝트의 Node.js 버전에 맞게 수정

            # 3. AWS 자격 증명 설정
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2 # ✅ S3 버킷이 있는 리전으로 수정 (서울은 ap-northeast-2)

            # 4. 의존성 패키지 설치
            - name: Install dependencies
              run: npm install

            # 5. React 프로젝트 빌드
            - name: Build React App
              run: npm run build

            # 6. 빌드된 파일을 S3에 업로드
            - name: Deploy to S3
              run: aws s3 sync ./build s3://wonny-front-bucket --delete # ✅ S3 버킷 이름 수정
              # --delete 옵션은 S3에 있지만 로컬 빌드 결과물에는 없는 파일을 삭제해줍니다. (정리용)

            # 7. (선택사항, 강력 추천) CloudFront 캐시 무효화
            - name: Invalidate CloudFront Cache
              run: aws cloudfront create-invalidation --distribution-id EZQPR7AVMT1JX --paths "/*" # ✅ CloudFront ID 수정
